#!/bin/sh

# Pas 2 instances
ps ax | grep -v grep | grep ' asimina_forms.jar'
if [ $? -eq 0 ]
then
exit 1
fi

PATH=/home/etn/bin:/usr/local/bin:/usr/bin:/bin

BASEDIR=$(dirname "$0")
cd "$BASEDIR"
java -jar    asimina_forms.jar    >> sched.log 2>&1 & 
echo $! >"$PWD"/sched.pid

exit 0
