#!/bin/sh

# Pas 2 instances
ps ax | grep -v grep | grep ' asimina_pages.jar com/etn/pages/SchedulerPartoo Scheduler.conf'
if [ $? -eq 0 ]
then
exit 1
fi

PATH="/usr/local/bin:/usr/bin:/bin:$PATH"

BASEDIR=$(dirname "$0")
cd "$BASEDIR"
java -cp asimina_pages.jar com/etn/pages/SchedulerPartoo Scheduler.conf   >> schedPartoo.log 2>&1 &
echo $! >"$PWD"/schedPartoo.pid

exit 0
