#!/bin/sh

# Pas 2 instances
ps ax | grep -v grep | grep ' asimina_pages.jar Scheduler.conf'
if [ $? -eq 0 ]
then
exit 1
fi

PATH="/usr/local/bin:/usr/bin:/bin:$PATH"

BASEDIR=$(dirname "$0")
cd "$BASEDIR"
java -jar asimina_pages.jar Scheduler.conf   >> sched.log 2>&1 &
echo $! >"$PWD"/sched.pid

exit 0
