#!/bin/sh

BASEDIR=$(dirname "$0")
cd "$BASEDIR"
touch _stopImpExp

mysql -u asimina cleandb_pages -h 127.0.0.1 -P 3306 -e "select semfree('D010');"
sleep 5

pid=`cat schedImportExport.pid`

kill -0 $pid 2>/dev/null && kill $pid 2>/dev/null

sleep 1
if kill -0 $pid 2>/dev/null
then
echo "echec terminaison $pid"
else
echo "$pid terminate"
fi

exit 0

